name: Spelling Errors Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: curl -L https://git.io/misspell | bash

    # This will return an exit code of 2, thus triggering a failed build
    - name: Test spelling errors
      shell: bash
      run: |
        bin/misspell -error *
